source "https://rubygems.org"

gem "jekyll", "~> 4.2.0"
gem "jekyll-theme-minimal", "~> 0.2.0"
gem "jekyll-feed", "~> 0.12"
gem "jekyll-seo-tag", "~> 2.6"
gem "jekyll-sitemap", "~> 1.4"

group :jekyll_plugins do
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
end 