name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: ['opened', 'reopened', 'synchronize']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16', '18']

    name: Node ${{ matrix.node }} build

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - name: install
        run: |
          npm install -g npm@latest
          npm ci
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
      - name: test
        run: jest --coverage && coveralls < coverage/lcov.info
      - name: docs
        run: npm run docs
      - name: Coveralls
        uses: coverallsapp/github-action@v2
