name: Build and Deploy Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: docs

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        working-directory: docs
        run: |
          gem install bundler
          bundle install

      - name: Build
        working-directory: docs
        run: bundle exec jekyll build --baseurl "${{ github.repository }}"

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs/_site

      - name: Deploy to Preview
        if: github.event_name == 'pull_request'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages-preview-${{ github.event.pull_request.number }}
          folder: docs/_site
          clean: true
          clean-exclude: |
            .git
            .github
            .gitignore 